name: check-cuda

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
    inputs:
      focce:
        description: 'focce rebase'
        required: false
        default: false
        type: boolean

jobs:
  check-cuda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check HTTP status
        uses: gerdemann/http-status-code@1.1.1
        with:
          url: https://developer.nvidia.com/cuda-toolkit-archive
          code: 200
      - name: Get git status
        id: git-status
        run: |
          git status -b -s > ${{ github.workspace }}/git-status.txt
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: git-status
          path: ${{ github.workspace }}/git-status.txt
      - name: Install dependencies and check for updates
        id: check-cuda
        run: |
          curl https://developer.nvidia.com/cuda-toolkit-archive -O
          sed -i '/<\/script><\/head><body class="html not-front/!d' cuda-toolkit-archive
          if git checkout origin/create-pull-request/cuda 2>/dev/null; then
            git fetch origin create-pull-request/cuda
          else
            git checkout -b create-pull-request/cuda
          fi
          git reset origin/create-pull-request/cuda
          git add .
          git commit -m A
          if git diff --ignore-space-at-eol --name-only origin/create-pull-request/cuda..HEAD -- cuda-toolkit-archive | grep . > /dev/null; then
            echo "update=true" >> $GITHUB_ENV
          else
            echo "update=false" >> $GITHUB_ENV
          fi
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: cuda-toolkit-archive
          path: cuda-toolkit-archive
      - name: Test
        id: test
        run: |
          if [ ${{ steps.check-cuda.outputs.update }} == true ]; then
            if git branch | grep create-pull-request/cuda > /dev/null; then
              git branch -D create-pull-request/cuda
            fi
            echo "test=true" >> $GITHUB_ENV
          else
            echo "test=false" >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        id: cpr
        if: ${{ steps.test.outputs.test == 'true' || (inputs.focce == true && always() ) }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[bot]update cuda-toolkit-archive"
          title: "update cuda-toolkit-archive"
          labels: cuda
          body: maybe update CUDA check [cuda-toolkit-archive](https://developer.nvidia.com/cuda-toolkit-archive)
          draft: true
          delete-branch: true
          branch: create-pull-request/cuda
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cuda-toolkit-archive
          path: cuda-toolkit-archive
